### PR TITLE
kr patch

### PR DESCRIPTION
**Pull request by jiyeonnn03**

### CODE REVIEW

**Comment by kvaps** [comment]
Hi thanks for contribution but your translation isn't working :(

I've added it into configuration file: https://github.com/candybox2/candybox2.github.io/commit/6c57acd517632379219c4b3fc3693aa29f7a1ed2

Please cherry-pick my commit and make `genText.py` working:

```
cd pythonScripts/
python genText.py
Traceback (most recent call last):
  File "genText.py", line 26, in <module>
    for index, line in enumerate(infile.readlines()):
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 22: invalid start byte
```

As can I see your format for the text file is little different in comparison with the other translations (eg. there extra lines with the spaces)

**Comment by kvaps** [comment]
Ok now text is compiling, but typescript compiler throws an error:

```
# ./compile.sh
code/gen/genText.ts(5670,20): error TS1005: ',' expected.
code/gen/genText.ts(5670,24): error TS1005: ',' expected.
code/gen/genText.ts(5670,25): error TS1127: Invalid character.
code/gen/genText.ts(5670,26): error TS1109: Expression expected.
code/gen/genText.ts(5670,31): error TS1005: ',' expected.
code/gen/genText.ts(5670,34): error TS1002: Unterminated string literal.
code/gen/genText.ts(5671,1): error TS1005: ',' expected.
code/gen/genText.ts(5671,44): error TS1005: ')' expected.
code/gen/genText.ts(6034,21): error TS1005: ',' expected.
code/gen/genText.ts(6034,23): error TS1005: ',' expected.
code/gen/genText.ts(6034,27): error TS1005: ',' expected.
code/gen/genText.ts(6034,30): error TS1005: ',' expected.
code/gen/genText.ts(6034,34): error TS1005: ',' expected.
code/gen/genText.ts(6034,39): error TS1005: ',' expected.
code/gen/genText.ts(6034,49): error TS1005: ',' expected.
code/gen/genText.ts(6034,52): error TS1005: ',' expected.
code/gen/genText.ts(6034,56): error TS1005: ',' expected.
code/gen/genText.ts(6034,59): error TS1005: ',' expected.
code/gen/genText.ts(6034,63): error TS1005: ',' expected.
code/gen/genText.ts(6034,72): error TS1005: ',' expected.
code/gen/genText.ts(6034,74): error TS1005: ',' expected.
code/gen/genText.ts(6034,88): error TS1002: Unterminated string literal.
code/gen/genText.ts(6035,1): error TS1005: ':' expected.
code/gen/genText.ts(6035,66): error TS1005: ')' expected.
code/gen/genText.ts(6039,83): error TS1005: ')' expected.
code/gen/genText.ts(6236,23): error TS1005: ')' expected.
```

**Comment by jiyeonnn03** [comment]
Wow, thanks!
But.. which part is the problem?
I don't know which part to modify...

**Comment by kvaps** [comment]
I don't know either, try to build project by yourself by calling `./compile.sh` script with your changes.

Sorry I have no enough time to debug it, so you probably can rely on your strength only :(

**Comment by kvaps** [comment]
Merged, thanks for the contribute!
Next time better create new git branch with your changes.

Cheers!

**Pull request merged**
